### ISSUE TITLE
simulation

### ISSUE THREAD

**Issue by Manojbhat09** [SoftServeSAG/spot_simulation#1]
Is the simulation for spot with Spot open SDK going to be with Webots or gazebo?
By when do you plan to release the code?

**Comment by tarasborov** [comment]
Hello! The simulation for Spot is for Gazebo. Please find the released code in the branches:
1) https://github.com/SoftServeSAG/spot_simulation/tree/spot_control
2) https://github.com/SoftServeSAG/spot_simulation/tree/spot_robomaker
3) https://github.com/SoftServeSAG/spot_simulation/tree/spot_towr
