### ISSUE TITLE
Teleop movement keys are flipped

### ISSUE THREAD

**Issue by sskorol** [SoftServeSAG/spot_simulation#10]
**Steps**:

- Follow the same preconditions as in https://github.com/SoftServeSAG/spot_simulation/issues/9
- Play with 1-6 keys to move Spot forward/backward/left/right/top/down and observe the behavior in Gazebo

**Expected**: Spot is moved according to CLI instructions
**Actual**: Spot's movements are flipped, e.g. when you press 1, it deviates backward; when you press 2 - forward, 3 - left, etc.

So Spot does the opposite actions in comparison to CLI instructions:

![Screenshot from 2021-12-10 11-54-25](https://user-images.githubusercontent.com/6638780/145554587-a737d121-da0e-41c1-be57-4750bc355ca9.png)

**Comment by tarasborov** [comment]
Thanks! Fixed.

**Comment by sskorol** [comment]
Confirm, thanks!
