### ISSUE TITLE
Without docker environment?

### ISSUE THREAD

**Issue by zhaozhongch** [SoftServeSAG/spot_simulation#2]
Thanks for the work! I am just wondering if this package can be run without docker?

**Comment by tarasborov** [comment]
Hello @zhaozhongch! 
Sure, the packages can be run without docker. For that make sure that ROS Melodic is installed locally on your machine. 
The usage of docker makes it more convenient to launch packages by automating the process of installing all dependincecies.

**Comment by zhaozhongch** [comment]
Thanks! This package really helps!
