### ISSUE TITLE
Setting up RViz on AWS RoboMaker?

### ISSUE THREAD

**Issue by jacksonyuanjx** [SoftServeSAG/spot_simulation#4]
Hi! Thanks for sharing this great repo! I'm fairly new to ROS and was wondering if you had any pointers on how I can get Spot's camera/sensor data as well as the simulated world to appear in RViz once launched into RoboMaker? Based on the `spot_robomaker` branch, I'm able to get a Gazebo environment working on RoboMaker but RViz and Rqt have not been displaying anything.

Any help would be much appreciated!

**Comment by tarasborov** [comment]
Hi @jacksonyuanjx! Thank you for contacting us. I am sorry for my late response. For now, the sensors are not attached to the model. It will be done in the near future. In addition, you can use our repo for tests for Spot on AWS RoboMaker: https://github.com/SoftServeSAG/aws_ros_spot_test
