### ISSUE TITLE
Broken key in the docker image

### ISSUE THREAD

**Issue by sskorol** [SoftServeSAG/spot_simulation#5]
Hi @tarasborov,

I tried to follow [README](https://github.com/SoftServeSAG/spot_simulation/blob/spot_control/README.md) and faced the following issue while building a docker image:

![Screenshot from 2021-12-09 11-11-15](https://user-images.githubusercontent.com/6638780/145367426-89ef7e5f-640d-43b3-ae38-f96c0d67795b.png)

Just Googled a fix for that here: https://answers.ros.org/question/325039/apt-update-fails-cannot-install-pkgs-key-not-working/

I added the following lines before doing update:
```bash
RUN sudo apt-key del 421C365BD9FF1F717815A3895523BAEEB01FA116
RUN sudo -E apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
```
Plus cleanup:
```bash
RUN sudo apt clean && apt-get update && apt-get install -y \
```
And it has been correctly built. So you may want to update your Dockerfile as well.

**Comment by tarasborov** [comment]
Thanks. The docker file was updated.
