### ISSUE TITLE
Failed to load joint points

### ISSUE THREAD

**Issue by sskorol** [SoftServeSAG/spot_simulation#6]
Hi @tarasborov @ldemk ,

When I use commands from README to load spot, there's a bunch of errors occur. Should I additionally start some services?
Note that `rosservice call controller_manager/list_controller_types` gives an error as well.
Would be greatly appreciated any help.

![Screenshot from 2021-12-09 15-39-36](https://user-images.githubusercontent.com/6638780/145407245-1378751c-e7da-448a-8015-35a6a87e976e.png)
![Screenshot from 2021-12-09 15-40-01](https://user-images.githubusercontent.com/6638780/145407266-e3822123-fe9f-4c2b-9b85-882eee43a5b3.png)
![Screenshot from 2021-12-09 15-43-16](https://user-images.githubusercontent.com/6638780/145407376-bea00bfe-7ef8-4d24-ba7e-ce3b239e7265.png)

Note that Spot appears in the world, but I can't do anything with it.

**Comment by tarasborov** [comment]
@sskorol Thanks for testing the repo. The issue was fixed, thus, run container again and follow instruction from README

**Comment by sskorol** [comment]
It works, thanks!
